# Generated by Django 4.1.4 on 2022-12-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0016_alter_sneaker_links'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favoriteSneakers',
            field=models.ManyToManyField(related_name='favorites', to='sneaker_app.sneaker'),
        ),
    ]
