# Generated by Django 4.1.4 on 2022-12-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_customuser_favoritesneakers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favoriteSneakers',
        ),
    ]
