# Generated by Django 4.1.4 on 2022-12-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='image',
            field=models.URLField(default='https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3cf0c669b07048cdb455ae02000e88df_9366/NMD_R1_Shoes_Pink_GZ4963_01_standard.jpg'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='price',
            field=models.IntegerField(),
        ),
    ]
