# Generated by Django 4.1.4 on 2022-12-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0002_sneaker_image_alter_sneaker_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
