# Generated by Django 4.1.4 on 2022-12-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0005_sneaker_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='price',
            field=models.IntegerField(default='Not Available'),
        ),
    ]
