# Generated by Django 4.1.4 on 2022-12-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0008_sneaker_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneaker',
            old_name='links',
            new_name='link',
        ),
    ]
