# Generated by Django 4.1.4 on 2022-12-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0009_rename_links_sneaker_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
