# Generated by Django 4.1.4 on 2022-12-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0014_rename_link_sneaker_links_sneaker_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='gender',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
