# Generated by Django 4.1.4 on 2022-12-15 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sneaker_app', '0016_alter_sneaker_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='user',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
