# Generated by Django 4.1.4 on 2022-12-15 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0017_sneaker_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneaker',
            old_name='user',
            new_name='users',
        ),
    ]
